from typing import *
# Sympy actually implements these as classes... shh, don't tell anybody
@overload
def factorial(n: int) -> int: ...
@overload
def factorial(n: float) -> float: ...
def subfactorial(n: int) -> int: ...
@overload
def binomial(n: int, k: int) -> int: ...
@overload
def binomial(n: float, k: Union[int, float]) -> float: ...
