from typing import *
# Sympy actually implements these as classes... shh, don't tell anybody
@overload
def fibonacci(n: int) -> int: ...
@overload
def fibonacci(n: float) -> float: ...
def lucas(n: int) -> int: ...
def bell(n: int) -> int: ...
def catalan(n: int) -> int: ...
